"""Controlled public workflow fixtures, with grading references kept offline.

These synthetic capability boundaries test orchestration mechanics. They do not
establish that real customer work intrinsically requires several agents.
"""
from __future__ import annotations

import json
import random
from collections.abc import Mapping
from dataclasses import dataclass, field
from types import MappingProxyType
from typing import Any

from conductor.datasets.integrity import digest
from conductor.schema import ExecutionState, Task

FAMILIES = ("retrieve_then_calculate", "retrieve_code_then_verify", "research_then_verify",
            "parallel_evidence_then_combine", "distractor_evidence_then_verify", "tool_failure_then_recover")
TASK_TYPE = "coordination_workflow"


def _freeze(value: Any) -> Any:
    if isinstance(value, Mapping):
        return MappingProxyType({str(key): _freeze(item) for key, item in value.items()})
    if isinstance(value, (list, tuple)):
        return tuple(_freeze(item) for item in value)
    return value


def _thaw(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {key: _thaw(item) for key, item in value.items()}
    if isinstance(value, tuple):
        return [_thaw(item) for item in value]
    return value


@dataclass(frozen=True)
class PublicStores:
    """Read-only resources; no task objects, answer keys or grader labels."""
    numeric_facts: Mapping[str, Any] = field(default_factory=dict)
    research_records: Mapping[str, Any] = field(default_factory=dict)
    tool_fixtures: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        for name in ("numeric_facts", "research_records", "tool_fixtures"):
            value = getattr(self, name)
            if not isinstance(value, Mapping) or any(not isinstance(key, str) for key in value):
                raise ValueError("public stores require string resource identifiers")
            object.__setattr__(self, name, _freeze(value))
        digest(self.to_dict())  # reject non-JSON/nonfinite resources

    def to_dict(self) -> dict[str, Any]:
        return {name: _thaw(getattr(self, name))
                for name in ("numeric_facts", "research_records", "tool_fixtures")}

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> PublicStores:
        if set(value) - {"numeric_facts", "research_records", "tool_fixtures"}:
            raise ValueError("unknown public-store fields")
        return cls(**dict(value))

    @property
    def corpus_sha256(self) -> str:
        return digest(self.to_dict())

    @property
    def source_ids(self) -> frozenset[str]:
        return frozenset((*self.numeric_facts, *self.research_records, *self.tool_fixtures))


def parse_request(value: ExecutionState | str) -> dict[str, Any]:
    request = json.loads(value.user_task if isinstance(value, ExecutionState) else value)
    if not isinstance(request, dict) or set(request) != {
            "request_id", "intent", "operation", "source_refs", "parameters", "verification"}:
        raise ValueError("workflow request has invalid public fields")
    if request["operation"] not in {"calculate", "transform", "research", "combine", "resolve_conflict", "read_tool"}:
        raise ValueError("unknown workflow operation")
    if (not isinstance(request["request_id"], str) or not isinstance(request["intent"], str)
            or not isinstance(request["source_refs"], dict) or not isinstance(request["parameters"], dict)
            or type(request["verification"]) is not bool):
        raise ValueError("invalid workflow public request types")
    return request


def _identifier(*parts: Any) -> str:
    return "ref_" + digest(list(parts))[:20]


def make_workload(*, seed: int = 314159, train_count: int = 72, dev_count: int = 36,
                  final_count: int = 0) -> tuple[list[Task], PublicStores]:
    """Generate explicit splits. Final data is never generated by default.

    Call final generation separately only after development choices are locked.
    Counts must be multiples of six to retain family coverage. Each final family
    has half known structures and half additional prerequisites/failure patterns.
    """
    counts = (train_count, dev_count, final_count)
    if any(type(number) is not int or number < 0 or number % len(FAMILIES) for number in counts) or not sum(counts):
        raise ValueError("nonnegative family-balanced counts, with at least one task, required")
    if final_count and final_count % (2 * len(FAMILIES)):
        raise ValueError("final inventory must split equally into known and structural-OOD tasks")
    randomizer = random.Random(seed)
    numeric, research, tools, tasks = {}, {}, {}, []
    for split, count in zip(("train", "dev", "test"), counts):
        per_family = count // len(FAMILIES)
        for index in range(count):
            family_number, sibling = index % len(FAMILIES), index // len(FAMILIES)
            family = FAMILIES[family_number]
            group = _identifier(seed, split, index, "problem")
            fact, record, tool, fallback, repair, replacement = (
                _identifier(group, label) for label in ("fact", "record", "tool", "fallback", "repair", "replacement"))
            value, factor, offset = randomizer.randint(20, 99), randomizer.randint(2, 7), randomizer.randint(2, 9)
            verification = bool(sibling % 2)
            ood = split == "test" and sibling >= per_family // 2
            source_refs: dict[str, Any] = {"fact_refs": [fact]}
            parameters: dict[str, Any] = {}
            local_numeric, local_research, local_tools = {}, {}, {}
            operation = ("calculate", "transform", "research", "combine", "resolve_conflict", "read_tool")[family_number]
            local_numeric[fact] = {"value": value, "unit": "count", "document": group}
            if operation == "calculate":
                parameters = {"factor": factor}
                expected = str(value * factor)
                if ood:
                    parameters["post_transform"] = "reverse_digits"
                    expected = expected[::-1]
                intent = "Retrieve the quantity and multiply by the requested factor."
            elif operation == "transform":
                parameters = {"transform": "reverse_digits"}
                expected = str(value)[::-1]
                if ood:
                    parameters["pre_scale"] = factor
                    expected = str(value * factor)[::-1]
                intent = "Retrieve the quantity and reverse its decimal digits."
            elif operation == "research":
                local_numeric[fact]["value"] = offset
                source_refs["research_refs"] = [record]
                local_research[record] = {"entries": [
                    {"revision": offset + 1, "value": str(value), "approved": True},
                    {"revision": offset + 3, "value": str(value + 1), "approved": False},
                    {"revision": offset + 2, "value": str(value + 2), "approved": True}]}
                parameters = {"query": "latest_approved_after_threshold"}
                expected = str(value + 2)
                if ood:
                    parameters["threshold_offset"] = 1
                intent = "Read the threshold, then research the latest approved revision above it."
            elif operation == "combine":
                source_refs["research_refs"] = [record]
                local_research[record] = {"rates": {"standard": factor, "alternate": factor + 2},
                                          "selected": "standard"}
                parameters = {"combine": "quantity_times_rate"}
                expected = str(value * factor)
                if ood:
                    source_refs["tool_ref"] = tool
                    parameters["rate_selector_from_tool"] = True
                    local_tools[tool] = {"value": "alternate", "failure": None}
                    expected = str(value * (factor + 2))
                intent = "Gather quantity and researched rate independently, then calculate their product."
            elif operation == "resolve_conflict":
                source_refs["research_refs"] = [record]
                local_numeric[fact]["value"] = value + 50
                local_numeric[fact]["notice"] = "Unconfirmed estimate; corroborate before using."
                local_research[record] = {"entries": [
                    {"value": str(value + 50), "revision": 9, "approved": False},
                    {"value": str(value), "revision": 2, "approved": True}]}
                parameters = {"query": "approved_value_over_unconfirmed_estimate"}
                expected = str(value)
                if ood:
                    parameters["post_transform"] = "reverse_digits"
                    expected = expected[::-1]
                intent = "Retrieve the estimate and reconcile it against approved research evidence."
            else:
                source_refs = {"tool_ref": tool}
                local_numeric = {fallback: {"value": value, "unit": "count", "document": group}}
                local_tools[tool] = {"value": str(value), "failure": "temporary_unavailable",
                                     "fallback_fact_ref": fallback}
                if ood:
                    local_tools[tool] = {"value": str(value), "failure": "stale_handle", "repair_record_ref": repair}
                    local_tools[replacement] = {"value": str(value), "failure": None}
                    local_research[repair] = {"replacement_tool_ref": replacement}
                    local_numeric = {}
                parameters = {"query": "read_counter_with_public_recovery"}
                expected = str(value)
                intent = "Read the counter using the public tool and recover from an actual error."
            if parameters.get("post_transform"):
                intent += " Then reverse the decimal digits of the resulting number."
            if parameters.get("pre_scale"):
                intent = "Retrieve the quantity, scale it, then reverse its decimal digits."
            if parameters.get("threshold_offset"):
                intent = "Retrieve and adjust the threshold before researching the eligible revision."
            if parameters.get("rate_selector_from_tool"):
                intent = "Read the rate selector from the tool before researching the rate; combine it with the quantity."
            intent += " Supply source-grounded verification evidence." if verification else " Supply source-grounded result evidence."
            request = {"request_id": group, "intent": intent, "operation": operation,
                       "source_refs": source_refs, "parameters": parameters, "verification": verification}
            text = json.dumps(request, sort_keys=True, separators=(",", ":"))
            snapshot = PublicStores(local_numeric, local_research, local_tools).to_dict()
            base_stages = (2, 2, 2, 2, 3, 2)[family_number]
            tasks.append(Task(digest(text)[:16], text, TASK_TYPE, split, expected,
                              {"family": family, "template_family": family, "source_group": group,
                               "problem_group": group, "dependency_stages": base_stages + int(ood) + int(verification),
                               "structure_id": operation + ("_extended" if ood else "_basic"),
                               "structure_ood": ood, "ood": ood, "grader": "coordination_workflow_v2",
                               "generation_seed": seed, "grading": {"public_stores": snapshot},
                               "scope": "controlled synthetic specialist capabilities"}))
            numeric.update(local_numeric)
            research.update(local_research)
            tools.update(local_tools)
    return tasks, PublicStores(numeric, research, tools)


def make_final_workload(*, seed: int, count: int = 120) -> tuple[list[Task], PublicStores]:
    """Explicit separate generation; caller must have locked protocol/choices."""
    return make_workload(seed=seed, train_count=0, dev_count=0, final_count=count)
